post http://localhost:4321/login
Content-Type: application/json

{
  "username": "emp@example.com",
  "password": "P@$$w0rd"
}

###
get http://localhost:4321/auth
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1AZXhhbXBsZS5jb20iLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsInJvbGVzIjpbIlVzdWFyaW9zIiwiQWRtaW5pc3RyYWRvcmVzIl0sImlhdCI6MTY4NDIzMjI4OCwiZXhwIjoxNjg0MjMyNTg4LCJhdWQiOiJhdXRob3JpemF0aW9uIiwiaXNzIjoiTWljcm9zZXJ2aWNpb3NKV1QifQ.g7hoZIowHHpHSjBAm2dHlVsSWWCFiR5vrKQRFwnh0Y7F_-qksUZsoVDo4FX_qBIRSpn2Kfn4yO_xHkX_CGO5dyxDsDuC1bI-G6_pFDcBWrkPJcuWfF2ZqsZB4RmYdXEX8wAuHWODRG6VbQQH_4_G1dCvml44NQ1hwuhMBNhpnpGtuFwudB1xjOFKR4YOA6gib1gKEBpYYU6WaeYHYi9cKpWbB_2FWCg-3wQzkVRFyrM_rIC-LNwrxpcCqNF7A5FAqxk8LWVEgpTa16GBRd1GC-TkE8A0xNej1lNGdALfV92yfRMHN3D9SahB0s2J5TC3slWSD59P62FQ3Nc78JKW-Q

###
post http://localhost:4321/login/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1AZXhhbXBsZS5jb20iLCJpYXQiOjE2ODQyMzIyODgsIm5iZiI6MTY4NDIzMjU4OCwiZXhwIjoxNjg0MjMzNDg4LCJhdWQiOiJhdXRob3JpemF0aW9uIiwiaXNzIjoiTWljcm9zZXJ2aWNpb3NKV1QifQ.s_wO18TnQpfHyla0f-DM8FVaJR-JM2E4maAMbrsZ6c0"
}

### 
get http://localhost:4321/api/libros
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJhZG1AZXhhbXBsZS5jb20iLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsInJvbGVzIjpbIlVzdWFyaW9zIiwiQWRtaW5pc3RyYWRvcmVzIl0sImlhdCI6MTY4NDIzMzI4OSwiZXhwIjoxNjg0MjMzNTg5LCJhdWQiOiJhdXRob3JpemF0aW9uIiwiaXNzIjoiTWljcm9zZXJ2aWNpb3NKV1QifQ.O535dO6iv1JZNzvL3PXEcn1f70u8mce7dyg8DAliicqXG37zp6Kw4chBrHHEUfZ0W-ehGvMj1J_My8MXbLw2LLLtHCzYb8BUO3kMYg0jlM05zkg1Jdj7Qt1gcHTfMYl1ZPKSlK5dTrXjeXTY2V2W1Rd3L2B_SBB3NpQidm-WCBoDo34yRSBUE0PgsislHfn4eMlBa9COp10_VOnzP2EPPdkxZN7-z0D8ik4DKOtl2mLN4WJJc1_RzHHSVJW8PTjUnozsQazABlJpTnoLul6NMToiIm9p847op9Rad6RiSSSRamdwmximmJaUz-2vVX6F2kwxkTFo6v79wjXVwqQ6gA

###
get http://localhost:4321/api/libros/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJlbXBAZXhhbXBsZS5jb20iLCJuYW1lIjoiRW1wbGVhZG8iLCJyb2xlcyI6WyJVc3VhcmlvcyIsIkVtcGxlYWRvcyJdLCJpYXQiOjE2ODQyMzQ4NzUsImV4cCI6MTY4NDIzNTE3NSwiYXVkIjoiYXV0aG9yaXphdGlvbiIsImlzcyI6Ik1pY3Jvc2VydmljaW9zSldUIn0.qgkSfIye3XFb1AH581SbKK23nqJKbCmU3-VF0tNhnFbGB09eWYGUYm-PMSYgfRkh1IhdhtYx9UJmD6QiT9ikEZCbH1-RSMfPjduM1RNXXGw9vU4rg_Y_DxdLT2O-Z3X4_AReQ3Jbo1mtt9b1yHPNynI5rPCSaJGnUxdOLH090cQ5AlSbF8m7RRAG7Nh2aHLpJWv1MDbZrt6EsJOChvtnCneXABnEx25CyebAFc-K1e4FPbbA5ETYmP2gexOdtgcEd7PXsUe1SgUJWTZHN9bmVlZiZJr5nOqCyaSqDy--sU4awKOuq7OP8QqzGCYsuxzBq_33g0b1FQLeL-wt369ukQ


###
PATCH http://localhost:4321/api/libros/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJlbXBAZXhhbXBsZS5jb20iLCJuYW1lIjoiRW1wbGVhZG8iLCJyb2xlcyI6WyJVc3VhcmlvcyIsIkVtcGxlYWRvcyJdLCJpYXQiOjE2ODQyMzQ4NzUsImV4cCI6MTY4NDIzNTE3NSwiYXVkIjoiYXV0aG9yaXphdGlvbiIsImlzcyI6Ik1pY3Jvc2VydmljaW9zSldUIn0.qgkSfIye3XFb1AH581SbKK23nqJKbCmU3-VF0tNhnFbGB09eWYGUYm-PMSYgfRkh1IhdhtYx9UJmD6QiT9ikEZCbH1-RSMfPjduM1RNXXGw9vU4rg_Y_DxdLT2O-Z3X4_AReQ3Jbo1mtt9b1yHPNynI5rPCSaJGnUxdOLH090cQ5AlSbF8m7RRAG7Nh2aHLpJWv1MDbZrt6EsJOChvtnCneXABnEx25CyebAFc-K1e4FPbbA5ETYmP2gexOdtgcEd7PXsUe1SgUJWTZHN9bmVlZiZJr5nOqCyaSqDy--sU4awKOuq7OP8QqzGCYsuxzBq_33g0b1FQLeL-wt369ukQ
Content-Type: application/json

{
    "paginas": "400"
}